[package]
name = "rust_chip-8_emulator"
version = "0.1.0"
authors = ["OngunAlpBaba"]
edition = "2018"
repository = ""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
